/*
 *    Copyright 2026 András Oravecz <info@oandras.hu>
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// Top-level build file where you can add configuration options common to all subprojects/modules.
import ksvg.gradle.registerCentralUpload

plugins {
    alias(libs.plugins.android.library) apply false
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.kotlin.android) apply false
    alias(libs.plugins.compose.compiler) apply false
    alias(libs.plugins.ksp) apply false
    alias(libs.plugins.dokka)
}

dokka {
    moduleName.set("KSVG")
    dokkaPublications.html {
        outputDirectory.set(layout.buildDirectory.dir("dokka"))
    }
    pluginsConfiguration.html {
        footerMessage.set("(c) András Oravecz")
    }
}

// Aggregates the public library modules into a single Dokka site
// (module selector in the header). Per-module Javadoc jars for Maven
// Central are still generated by each module's own dokka config.
//
// NOTE: :filtering is deliberately excluded: it is an internal
// implementation detail (transitive dep of :ksvg, public only because
// cross-module/JNI calls require it), not a supported API surface.
// Its Javadoc jar is still published alongside the artifact.
dependencies {
    dokka(project(":ksvg"))
    dokka(project(":glide"))
    dokka(project(":compose"))
}

subprojects {
    tasks.withType<Test> {
        testLogging {
            showStandardStreams = project.hasProperty("showTestOutput")
        }
    }
}

// Maven Central Publisher Portal bundle upload (signed staging repo ->
// portal deployment). Credentials via -PcentralUsername/-PcentralPassword,
// ~/.gradle/gradle.properties, or CENTRAL_USERNAME/CENTRAL_PASSWORD;
// never logged, never committed.
registerCentralUpload()