/*
 *    Copyright 2013-2020 Paul LeBeau, Cave Rock Software Ltd.
 *    Copyright 2026 András Oravecz <info@oandras.hu>
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

package hu.oandras.ksvg.parser

import hu.oandras.ksvg.dom.COLOR_BLACK

// Standard SVG/CSS color keywords
@Suppress("SpellCheckingInspection")
internal object ColorKeywords {

    fun get(colorName: String): Int = when (colorName) {
        "aliceblue" -> 0xFFF0F8FF.toInt()
        "antiquewhite" -> 0xFFFAEBD7.toInt()
        "aqua" -> 0xFF00FFFF.toInt()
        "aquamarine" -> 0xFF7FFFD4.toInt()
        "azure" -> 0xFFF0FFFF.toInt()
        "beige" -> 0xFFF5F5DC.toInt()
        "bisque" -> 0xFFFFE4C4.toInt()
        "black" -> COLOR_BLACK
        "blanchedalmond" -> 0xFFFFEBCD.toInt()
        "blue" -> 0xFF0000FF.toInt()
        "blueviolet" -> 0xFF8A2BE2.toInt()
        "brown" -> 0xFFA52A2A.toInt()
        "burlywood" -> 0xFFDEB887.toInt()
        "cadetblue" -> 0xFF5F9EA0.toInt()
        "chartreuse" -> 0xFF7FFF00.toInt()
        "chocolate" -> 0xFFD2691E.toInt()
        "coral" -> 0xFFFF7F50.toInt()
        "cornflowerblue" -> 0xFF6495ED.toInt()
        "cornsilk" -> 0xFFFFF8DC.toInt()
        "crimson" -> 0xFFDC143C.toInt()
        "cyan" -> 0xFF00FFFF.toInt()
        "darkblue" -> 0xFF00008B.toInt()
        "darkcyan" -> 0xFF008B8B.toInt()
        "darkgoldenrod" -> 0xFFB8860B.toInt()
        "darkgray" -> 0xFFA9A9A9.toInt()
        "darkgreen" -> 0xFF006400.toInt()
        "darkgrey" -> 0xFFA9A9A9.toInt()
        "darkkhaki" -> 0xFFBDB76B.toInt()
        "darkmagenta" -> 0xFF8B008B.toInt()
        "darkolivegreen" -> 0xFF556B2F.toInt()
        "darkorange" -> 0xFFFF8C00.toInt()
        "darkorchid" -> 0xFF9932CC.toInt()
        "darkred" -> 0xFF8B0000.toInt()
        "darksalmon" -> 0xFFE9967A.toInt()
        "darkseagreen" -> 0xFF8FBC8F.toInt()
        "darkslateblue" -> 0xFF483D8B.toInt()
        "darkslategray" -> 0xFF2F4F4F.toInt()
        "darkslategrey" -> 0xFF2F4F4F.toInt()
        "darkturquoise" -> 0xFF00CED1.toInt()
        "darkviolet" -> 0xFF9400D3.toInt()
        "deeppink" -> 0xFFFF1493.toInt()
        "deepskyblue" -> 0xFF00BFFF.toInt()
        "dimgray" -> 0xFF696969.toInt()
        "dimgrey" -> 0xFF696969.toInt()
        "dodgerblue" -> 0xFF1E90FF.toInt()
        "firebrick" -> 0xFFB22222.toInt()
        "floralwhite" -> 0xFFFFFAF0.toInt()
        "forestgreen" -> 0xFF228B22.toInt()
        "fuchsia" -> 0xFFFF00FF.toInt()
        "gainsboro" -> 0xFFDCDCDC.toInt()
        "ghostwhite" -> 0xFFF8F8FF.toInt()
        "gold" -> 0xFFFFD700.toInt()
        "goldenrod" -> 0xFFDAA520.toInt()
        "gray" -> 0xFF808080.toInt()
        "green" -> 0xFF008000.toInt()
        "greenyellow" -> 0xFFADFF2F.toInt()
        "grey" -> 0xFF808080.toInt()
        "honeydew" -> 0xFFF0FFF0.toInt()
        "hotpink" -> 0xFFFF69B4.toInt()
        "indianred" -> 0xFFCD5C5C.toInt()
        "indigo" -> 0xFF4B0082.toInt()
        "ivory" -> 0xFFFFFFF0.toInt()
        "khaki" -> 0xFFF0E68C.toInt()
        "lavender" -> 0xFFE6E6FA.toInt()
        "lavenderblush" -> 0xFFFFF0F5.toInt()
        "lawngreen" -> 0xFF7CFC00.toInt()
        "lemonchiffon" -> 0xFFFFFACD.toInt()
        "lightblue" -> 0xFFADD8E6.toInt()
        "lightcoral" -> 0xFFF08080.toInt()
        "lightcyan" -> 0xFFE0FFFF.toInt()
        "lightgoldenrodyellow" -> 0xFFFAFAD2.toInt()
        "lightgray" -> 0xFFD3D3D3.toInt()
        "lightgreen" -> 0xFF90EE90.toInt()
        "lightgrey" -> 0xFFD3D3D3.toInt()
        "lightpink" -> 0xFFFFB6C1.toInt()
        "lightsalmon" -> 0xFFFFA07A.toInt()
        "lightseagreen" -> 0xFF20B2AA.toInt()
        "lightskyblue" -> 0xFF87CEFA.toInt()
        "lightslategray" -> 0xFF778899.toInt()
        "lightslategrey" -> 0xFF778899.toInt()
        "lightsteelblue" -> 0xFFB0C4DE.toInt()
        "lightyellow" -> 0xFFFFFFE0.toInt()
        "lime" -> 0xFF00FF00.toInt()
        "limegreen" -> 0xFF32CD32.toInt()
        "linen" -> 0xFFFAF0E6.toInt()
        "magenta" -> 0xFFFF00FF.toInt()
        "maroon" -> 0xFF800000.toInt()
        "mediumaquamarine" -> 0xFF66CDAA.toInt()
        "mediumblue" -> 0xFF0000CD.toInt()
        "mediumorchid" -> 0xFFBA55D3.toInt()
        "mediumpurple" -> 0xFF9370DB.toInt()
        "mediumseagreen" -> 0xFF3CB371.toInt()
        "mediumslateblue" -> 0xFF7B68EE.toInt()
        "mediumspringgreen" -> 0xFF00FA9A.toInt()
        "mediumturquoise" -> 0xFF48D1CC.toInt()
        "mediumvioletred" -> 0xFFC71585.toInt()
        "midnightblue" -> 0xFF191970.toInt()
        "mintcream" -> 0xFFF5FFFA.toInt()
        "mistyrose" -> 0xFFFFE4E1.toInt()
        "moccasin" -> 0xFFFFE4B5.toInt()
        "navajowhite" -> 0xFFFFDEAD.toInt()
        "navy" -> 0xFF000080.toInt()
        "oldlace" -> 0xFFFDF5E6.toInt()
        "olive" -> 0xFF808000.toInt()
        "olivedrab" -> 0xFF6B8E23.toInt()
        "orange" -> 0xFFFFA500.toInt()
        "orangered" -> 0xFFFF4500.toInt()
        "orchid" -> 0xFFDA70D6.toInt()
        "palegoldenrod" -> 0xFFEEE8AA.toInt()
        "palegreen" -> 0xFF98FB98.toInt()
        "paleturquoise" -> 0xFFAFEEEE.toInt()
        "palevioletred" -> 0xFFDB7093.toInt()
        "papayawhip" -> 0xFFFFEFD5.toInt()
        "peachpuff" -> 0xFFFFDAB9.toInt()
        "peru" -> 0xFFCD853F.toInt()
        "pink" -> 0xFFFFC0CB.toInt()
        "plum" -> 0xFFDDA0DD.toInt()
        "powderblue" -> 0xFFB0E0E6.toInt()
        "purple" -> 0xFF800080.toInt()
        "rebeccapurple" -> 0xFF663399.toInt()
        "red" -> 0xFFFF0000.toInt()
        "rosybrown" -> 0xFFBC8F8F.toInt()
        "royalblue" -> 0xFF4169E1.toInt()
        "saddlebrown" -> 0xFF8B4513.toInt()
        "salmon" -> 0xFFFA8072.toInt()
        "sandybrown" -> 0xFFF4A460.toInt()
        "seagreen" -> 0xFF2E8B57.toInt()
        "seashell" -> 0xFFFFF5EE.toInt()
        "sienna" -> 0xFFA0522D.toInt()
        "silver" -> 0xFFC0C0C0.toInt()
        "skyblue" -> 0xFF87CEEB.toInt()
        "slateblue" -> 0xFF6A5ACD.toInt()
        "slategray" -> 0xFF708090.toInt()
        "slategrey" -> 0xFF708090.toInt()
        "snow" -> 0xFFFFFAFA.toInt()
        "springgreen" -> 0xFF00FF7F.toInt()
        "steelblue" -> 0xFF4682B4.toInt()
        "tan" -> 0xFFD2B48C.toInt()
        "teal" -> 0xFF008080.toInt()
        "thistle" -> 0xFFD8BFD8.toInt()
        "tomato" -> 0xFFFF6347.toInt()
        "turquoise" -> 0xFF40E0D0.toInt()
        "violet" -> 0xFFEE82EE.toInt()
        "wheat" -> 0xFFF5DEB3.toInt()
        "white" -> 0xFFFFFFFF.toInt()
        "whitesmoke" -> 0xFFF5F5F5.toInt()
        "yellow" -> 0xFFFFFF00.toInt()
        "yellowgreen" -> 0xFF9ACD32.toInt()
        "transparent" -> 0x00000000
        else -> COLOR_BLACK
    }
}
